language: go

go:
  - 1.4.1

services:
  - rabbitmq

matrix:
  fast_finish: true

# Only build pushes to the master branch (and PRs)
branches:
  only:
    - master

sudo: required

before_install:
  - sudo mkdir /etc/letsencrypt
  - sudo chown $USER /etc/letsencrypt
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - git clone https://www.github.com/letsencrypt/lets-encrypt-preview.git /tmp/letsencrypt
  - cd /tmp/letsencrypt
  - sudo ./bootstrap/debian.sh
  - virtualenv --no-site-packages -p python2 ./venv
  - ./venv/bin/pip install -r requirements.txt -e .
  - "cd -"

env:
  - LETSENCRYPT_VENV=/tmp/letsencrypt/venv

script:
  - make -j4 # Travis has 2 cores per build instance
  - bash test.sh
