language: go
dist: xenial
os: linux

go:
  - "1.15rc2"
  - "1.14.5"

go_import_path: github.com/letsencrypt/boulder

services:
  - docker

# Only build pushes to the main branch, PRs, and branches beginning with
# `test-`. You should not push branches beginning with `test-` to the
# letsencrypt repository, but this is a convenient way to push branches to your
# own fork of the repository to ensure Travis passes before submitting a PR.
# For instance, you might run:
# git push myremote branchname:test-branchname
branches:
  only:
    - main
    - /^test-.*$/

env:
    - RUN="integration" BOULDER_CONFIG_DIR="test/config-next"

jobs:
  fast_finish: true

install:
  - docker-compose pull

script:
  - >-
    docker-compose run --use-aliases
    -e BOULDER_CONFIG_DIR
    -e RUN
    -e TRAVIS_BRANCH
    -e TRAVIS_JOB_ID
    -e TRAVIS_PULL_REQUEST
    -e COVERALLS_TOKEN
    ${CONTAINER:-boulder} ./test.sh
