language: go

go:
  - 1.8.3

addons:
  hosts:
    - le.wtf
    - boulder
    - boulder-mysql
    - boulder-rabbitmq

sudo: required

services:
  - docker

matrix:
  fast_finish: true

# Only build pushes to the master branch, PRs, and branches beginning with
# `test-`. You should not push branches beginning with `test-` to the
# letsencrypt repository, but this is a convenient way to push branches to your
# own fork of the repostiroy to ensure Travis passes before submitting a PR.
# For instance, you might run:
# git push myremote branchname:test-branchname
branches:
  only:
    - master
    - staging
    - release
    - /^test-.*$/

install:
  - ./test/travis-before-install.sh
  - docker-compose pull
  - docker-compose build

script:
  - /sbin/ifconfig
